build:
  cuda_version: "12.1.1"
  python_version: "3.10"
  system_packages:
    - "git"
  python_packages:
    - "inferless-cli==2.0.9"
    - "pydantic"
    - "accelerate"
    - "git+https://github.com/huggingface/diffusers.git"
    - "torch"
    - "transformers==4.42.4"
    - "xformers"
    - "protobuf"
    - "sentencepiece"
    - "watchdog"
    - "websockets"
  run:
    - "git clone https://huggingface.co/spaces/dangthr/FLUX.1-Krea-dev.git"